Do minimal entity interpretation.

diff --git a/tests/run-test b/tests/run-test
--- a/tests/run-test
+++ b/tests/run-test
@@ -117,6 +117,10 @@ function fixName {
         echo "Missing expected output for: ${name}" 1>&2
     fi
 
+    if [[ ! -r ${dir}/README.md ]]; then
+        echo "Missing test description for: ${name}" 1>&2
+    fi
+
     echo "${dir}"
 }
 
@@ -172,6 +176,8 @@ function runTest {
         cp actual.txt "${dir}/expected.txt"
         return 0
     else
+        echo ''
+        cat README.md
         echo ''
         echo 'ERROR: Expected and actual output differ!'
         echo ''
